memory_arena: arena_debug.c File Reference
arena_debug.c File Reference
Debugging and Validation
Debugging, error reporting, memory poisoning, and integrity checking utilities for the Arena memory allocation system.
#include "arena_debug.h"
#include "arena.h"
#include "arena_stats.h"
#include <stdarg.h>
#include <stdatomic.h>
#include <stdio.h>
#include <string.h>
Functions
void arena_default_error_callback (const char *msg, void *ctx)
void arena_generate_id (t_arena *arena)
void arena_report_error (t_arena *arena, const char *fmt,...)
void arena_set_debug_label (t_arena *arena, const char *label)
void arena_set_error_callback (t_arena *arena, arena_error_callback cb, void *context)
Variables
static atomic_int g_arena_id_counter = 0
Global atomic counter for generating unique arena IDs.
Detailed Description
Debugging, error reporting, memory poisoning, and integrity checking utilities for the Arena memory allocation system.
Author
Toonsa
Date
2025
This module provides diagnostic tools and debug features for tracking arena state, reporting errors, and catching incorrect memory usage patterns. It includes:
Unique ID generation for arenas (arena_generate_id)
Human-readable debug labels (arena_set_debug_label)
Customizable error reporting with callbacks (arena_set_error_callback)
Default and formatted error output (arena_report_error)
Memory poisoning (arena_poison_memory) to detect use-after-reset bugs
Internal consistency checks (arena_integrity_check) for development and testing
All features are modular and gated by compile-time flags to avoid overhead in release builds:
ARENA_DEBUG_CHECKS enables runtime assertions and state validation.
ARENA_POISON_MEMORY enables memory poisoning.
ARENA_DEBUG_LOG enables optional debug logging via ALOG(...).
These utilities are intended to support:
Arena-based memory debugging in development
Integration with tooling (profilers, visualizers)
Unit tests that verify correctness of memory behavior
Note
The debug system is opt-in and safe for multithreaded use when enabled. For minimal runtime cost, features can be selectively toggled via macros.
Definition in file arena_debug.c.
Function Documentation
arena_default_error_callback()
void arena_default_error_callback (const char * msg, void * ctx)
Definition at line 310 of file arena_debug.c.
{
    (void) ctx;
    fprintf(stderr, "[ARENA ERROR] %s\n", msg);
}
Referenced by arena_reset_metadata(), and arena_set_error_callback().
arena_generate_id()
void arena_generate_id (t_arena * arena)
Definition at line 102 of file arena_debug.c.
{
    if (!arena)
        return;
    snprintf(arena->debug.id, ARENA_ID_LEN, "A#%04d", atomic_fetch_add(&g_arena_id_counter, 1));
}
References ARENA_ID_LEN, and g_arena_id_counter.
Referenced by arena_create(), arena_finish_init(), arena_init(), and arena_init_with_buffer().
arena_report_error()
void arena_report_error (t_arena * arena, const char * fmt, ...)
Definition at line 253 of file arena_debug.c.
{
    va_list args;
    va_start(args, fmt);
    char message[512];
    vsnprintf(message, sizeof(message), fmt, args);
    va_end(args);
    if (arena && arena->debug.error_cb)
    {
        arena->debug.error_cb(message, arena->debug.error_context);
    }
    else
    {
        fprintf(stderr, "[ARENA ERROR]");
        if (arena && arena->debug.label)
            fprintf(stderr, " (%s)", arena->debug.label);
        fprintf(stderr, " %s\n", message);
    }
}
Referenced by arena_alloc_buffer(), arena_alloc_internal(), arena_alloc_sub_labeled_aligned(), arena_alloc_sub_validate(), arena_alloc_validate_input(), arena_calloc_aligned_labeled(), arena_check_overflow(), arena_create(), arena_grow(), arena_grow_realloc_buffer(), arena_grow_validate(), arena_init(), arena_init_mutex(), arena_init_with_buffer(), arena_log_and_teardown(), arena_pop(), arena_realloc_validate(), arena_set_allocated_buffer(), arena_set_allocation_hook(), arena_try_grow(), destroy_thread_scratch_arena(), get_thread_scratch_arena(), get_thread_scratch_arena_ref(), realloc_in_place(), scratch_acquire(), scratch_pool_init(), scratch_release(), scratch_slot_init(), set_thread_scratch_arena_size(), and validate_arena_calloc_input().
arena_set_debug_label()
void arena_set_debug_label (t_arena * arena, const char * label)
Definition at line 147 of file arena_debug.c.
{
    if (arena)
        arena->debug.label = label;
}
Referenced by arena_setup_subarena().
arena_set_error_callback()
void arena_set_error_callback (t_arena * arena, arena_error_callback cb, void * context)
Definition at line 201 of file arena_debug.c.
{
    if (!arena)
        return;
    arena->debug.error_cb      = cb ? cb : arena_default_error_callback;
    arena->debug.error_context = cb ? context : NULL;
}
References arena_default_error_callback().