memory_arena: arena_cleanup.c File Reference
arena_cleanup.c File Reference
Arena Cleanup
Cleanup and teardown routines for memory arenas.
#include "arena.h"
Functions
void arena_delete (t_arena **arena)
void arena_destroy (t_arena *arena)
static void arena_free_buffer_if_owned (t_arena *arena)
Free the arena's internal buffer if the arena owns it.
static void arena_free_growth_history (t_arena *arena)
Free the memory used to store the arena's growth history.
Detailed Description
Cleanup and teardown routines for memory arenas.
Author
Toonsa
Date
2025
This file provides functions to safely destroy and deallocate arena resources, including internal memory buffers, metadata like growth history, and synchronization primitives. It ensures proper cleanup whether the arena is heap-allocated or stack-allocated.
API functions included:
Thread-safe destruction (arena_destroy)
Full arena deletion (arena_delete)
These functions are used internally and publicly to manage arena lifecycles and to ensure memory safety, thread-safety, and diagnostic cleanliness.
Definition in file arena_cleanup.c.
Function Documentation
arena_delete()
void arena_delete (t_arena ** arena)
Definition at line 148 of file arena_cleanup.c.
{
    if (!arena || !*arena)
        return;
    arena_destroy(*arena);
    free(*arena);
    *arena = NULL;
}
References arena_destroy().
Referenced by arena_log_and_teardown().
arena_destroy()
void arena_destroy (t_arena * arena)
Definition at line 82 of file arena_cleanup.c.
{
    if (!arena)
        return;
    bool expected = false;
    if (!atomic_compare_exchange_strong(&arena->is_destroying, &expected, true))
        return;
#ifdef ARENA_ENABLE_THREAD_SAFE
    if (arena->use_lock)
    {
        ARENA_CHECK(arena);
        ARENA_LOCK(arena);
        arena_free_buffer_if_owned(arena);
        arena_free_growth_history(arena);
        arena_zero_metadata(arena);
        ARENA_UNLOCK(arena);
        arena->use_lock = false;
        pthread_mutex_destroy(&arena->lock);
        return;
    }
#endif
    arena_free_buffer_if_owned(arena);
    arena_free_growth_history(arena);
    arena_zero_metadata(arena);
}
References ARENA_CHECK, arena_free_buffer_if_owned(), arena_free_growth_history(), ARENA_LOCK, ARENA_UNLOCK, and arena_zero_metadata().
Referenced by arena_delete(), arena_log_and_teardown(), arena_reinit_with_buffer(), and scratch_pool_destroy().