memory_arena: arena_resize.c File Reference
arena_resize.c File Reference
Arena Resize
Arena memory resizing logic — dynamic growth and shrinking.
#include "arena.h"
#include <math.h>
Functions
static bool arena_can_shrink (t_arena *arena, size_t new_size)
Determine whether the arena is eligible for shrinking to a smaller size.
bool arena_grow (t_arena *arena, size_t required_size)
static size_t arena_grow_compute_new_size (t_arena *arena, size_t required_size)
Compute the new size for the arena based on the growth policy.
static bool arena_grow_realloc_buffer (t_arena *arena, size_t new_size, size_t old_size)
Reallocate the arena's buffer to a new size.
static bool arena_grow_validate (t_arena *arena, size_t required_size)
Validate whether the arena is allowed to grow for a given request.
bool arena_might_shrink (t_arena *arena)
static void arena_record_growth (t_arena *arena, size_t old_size)
Record the previous size of the arena in the growth history.
static bool arena_should_grow (const t_arena *arena)
Check whether the arena is allowed to grow.
static bool arena_should_maybe_shrink (size_t used, size_t size)
Decide whether the arena buffer should be shrunk based on usage ratio.
void arena_shrink (t_arena *arena, size_t new_size)
static bool arena_shrink_apply (t_arena *arena, size_t new_size)
Apply the memory shrink operation to an arena's buffer.
static size_t arena_shrink_target (size_t used)
Compute the target buffer size for a shrink operation.
static bool arena_shrink_validate (t_arena *arena, size_t new_size)
Validate whether an arena can be safely shrunk to a new size.
static bool should_attempt_shrink (t_arena *arena)
Determine whether the arena is eligible for dynamic shrinking.
Detailed Description
Arena memory resizing logic — dynamic growth and shrinking.
Author
Toonsa
Date
2025
This file implements the dynamic memory resizing features of the arena allocator, allowing it to grow when allocations exceed current capacity, and shrink when memory usage drops significantly.
Features covered in this file:
Manual growth (arena_grow) based on requested size.
Automatic resizing policy through user-defined or default callbacks.
Shrinking (arena_shrink) of underused memory regions.
Heuristic-based auto-shrinking (arena_might_shrink) with safe thresholds.
Internal helpers for validation, computation, and buffer reallocation.
All operations are thread-safe and acquire internal locks on the arena during mutation of memory size or related metadata.
This module is especially useful for long-lived arenas in high-uptime applications, where memory usage patterns may fluctuate and reclaiming unused memory is desirable.
Note
The resizing logic assumes the arena owns its buffer and is marked as growable. Shrinking operations are designed to be conservative to prevent thrashing.
Definition in file arena_resize.c.
Function Documentation
arena_grow()
bool arena_grow (t_arena * arena, size_t required_size)
Definition at line 59 of file arena_resize.c.
{
    if (!arena)
        return false;
    if (required_size == 0)
        return true;
    ARENA_LOCK(arena);
    if (!arena_grow_validate(arena, required_size))
    {
        ARENA_UNLOCK(arena);
        return false;
    }
    size_t old_size = arena->size;
    size_t new_size = arena_grow_compute_new_size(arena, required_size);
    if (new_size == 0)
    {
        arena_report_error(arena, "arena_grow failed: computed size invalid");
        ARENA_UNLOCK(arena);
        return false;
    }
    if (new_size > (size_t)(1ULL << 32)) // 4GiB
    {
        arena_report_error(arena, "arena_grow rejected size: %zu", new_size);
        return false;
    }
    bool success = arena_grow_realloc_buffer(arena, new_size, old_size);
    ARENA_UNLOCK(arena);
    return success;
}
References arena_grow_compute_new_size(), arena_grow_realloc_buffer(), arena_grow_validate(), ARENA_LOCK, arena_report_error(), and ARENA_UNLOCK.
Referenced by arena_try_grow(), and realloc_in_place().
arena_might_shrink()
bool arena_might_shrink (t_arena * arena)
Definition at line 108 of file arena_resize.c.
{
    if (!should_attempt_shrink(arena))
        return false;
    ARENA_LOCK(arena);
    ARENA_CHECK(arena);
    const size_t used = arena->offset;
    const size_t size = arena->size;
    if (arena_should_maybe_shrink(used, size))
    {
        const size_t target = arena_shrink_target(used);
        if (target < size)
        {
            arena_shrink(arena, target);
            ARENA_UNLOCK(arena);
            return true;
        }
    }
    ARENA_UNLOCK(arena);
    return false;
}
References ARENA_CHECK, ARENA_LOCK, arena_should_maybe_shrink(), arena_shrink(), arena_shrink_target(), ARENA_UNLOCK, should_attempt_shrink(), and used.
arena_shrink()
void arena_shrink (t_arena * arena, size_t new_size)
Definition at line 94 of file arena_resize.c.
{
    if (!arena)
        return;
    ARENA_LOCK(arena);
    ARENA_CHECK(arena);
    bool ok = arena_shrink_validate(arena, new_size) && arena_shrink_apply(arena, new_size);
    (void) ok;
    ARENA_UNLOCK(arena);
}
References ARENA_CHECK, ARENA_LOCK, arena_shrink_apply(), arena_shrink_validate(), and ARENA_UNLOCK.
Referenced by arena_might_shrink().