memory_arena: arena_stack.c File Reference
arena_stack.c File Reference
Arena State Management
Stack-based scoped memory management for arenas.
#include "arena_stack.h"
#include <stdlib.h>
Functions
void arena_stack_clear (t_arena_stack *stack)
Clear all frames in the arena stack without altering arena memory.
void arena_stack_init (t_arena_stack *stack, t_arena *arena)
void arena_stack_pop (t_arena_stack *stack)
void arena_stack_push (t_arena_stack *stack)
Detailed Description
Stack-based scoped memory management for arenas.
Author
Toonsa
Date
2025
This module implements a lightweight stack system on top of arena-based memory. It allows users to push and pop memory states using marker frames allocated within the arena itself. This pattern enables efficient and structured management of temporary memory regions.
Core functionality includes:
Tracking memory states using arena_mark() saved as stack frames.
Reverting to a previous memory state via arena_pop().
Grouping allocations into push/pop memory scopes (similar to RAII or region-based memory).
Optional stack clearing without altering the arena state.
All stack frames are stored inside the arena, meaning no additional heap allocations or deallocations are required.
Typical use cases:
Nested parsing stages or recursive algorithms.
Temporary memory for intermediate steps in complex logic.
Systems requiring fast and deterministic memory rollback.
Note
Stack operations (push, pop, clear) are local to the arena and safe to use as long as the arena is not destroyed or reset externally.
Definition in file arena_stack.c.
Function Documentation
arena_stack_init()
void arena_stack_init (t_arena_stack * stack, t_arena * arena)
Definition at line 144 of file arena_stack.c.
{
    if (!stack || !arena)
        return;
    stack->arena = arena;
    stack->top   = NULL;
}
References s_arena_stack::arena, and s_arena_stack::top.
arena_stack_pop()
void arena_stack_pop (t_arena_stack * stack)
Definition at line 254 of file arena_stack.c.
{
    if (!stack || !stack->arena || !stack->top)
        return;
    arena_pop(stack->arena, stack->top->marker);
    stack->top = stack->top->prev;
}
References s_arena_stack::arena, arena_pop(), s_arena_stack_frame::marker, s_arena_stack_frame::prev, and s_arena_stack::top.
arena_stack_push()
void arena_stack_push (t_arena_stack * stack)
Definition at line 197 of file arena_stack.c.
{
    if (!stack || !stack->arena)
        return;
    t_arena_stack_frame* frame = (t_arena_stack_frame*) arena_alloc(stack->arena, sizeof(t_arena_stack_frame));
    if (!frame)
        return;
    frame->marker = arena_mark(stack->arena);
    frame->prev   = stack->top;
    stack->top    = frame;
}
References s_arena_stack::arena, arena_alloc(), arena_mark(), s_arena_stack_frame::marker, s_arena_stack_frame::prev, and s_arena_stack::top.