memory_arena: Arena Allocation Internals
Arena Allocation Internals
Internal Implementation
Internal helpers for memory allocation logic.
Functions
void * arena_alloc_internal (t_arena *arena, size_t size, size_t alignment, const char *label)
Core internal allocator with alignment and labeling support.
static bool arena_alloc_validate_input (t_arena *arena, size_t size, size_t alignment, const char *label)
Validate input parameters for arena allocation.
static size_t arena_calc_aligned_offset (t_arena *arena, size_t alignment)
Compute the next aligned offset within the arena.
static bool arena_check_overflow (t_arena *arena, size_t size, const char *label)
Check whether an allocation would cause a size_t overflow.
static void arena_commit_allocation (t_arena *arena, size_t size, size_t wasted, size_t aligned_offset)
Update offset, peak usage, and statistics.
static bool arena_ensure_capacity (t_arena *arena, size_t size, size_t alignment, const char *label, size_t *aligned_offset, size_t *wasted)
Ensure that the arena has enough space for a new allocation with alignment.
static void arena_invoke_allocation_hook (t_arena *arena, void *ptr, size_t size, size_t offset, size_t wasted, const char *label)
Invoke the user-defined allocation hook, if registered.
static bool arena_is_being_destroyed (t_arena *arena, const char *label)
Check whether the arena is currently being destroyed.
static bool arena_realloc_validate (t_arena *arena, void *old_ptr, size_t new_size)
Validate input arguments for arena_realloc_last.
static bool arena_try_grow (t_arena *arena, size_t size, const char *label)
Attempt to grow the arena's buffer to satisfy an upcoming allocation.
static void arena_update_stats (t_arena *arena, size_t size, size_t wasted)
Update allocation statistics after a successful arena allocation.
static void arena_zero_if_needed (void *ptr, size_t size, const char *label)
Zero or poison a memory region depending on allocation label.
static bool is_last_allocation (t_arena *arena, void *old_ptr, size_t old_size)
Check if a given pointer corresponds to the most recent allocation.
static void * realloc_fallback (t_arena *arena, void *old_ptr, size_t old_size, size_t new_size)
Perform a fallback reallocation by allocating new memory and copying data.
static void * realloc_in_place (t_arena *arena, void *old_ptr, size_t old_size, size_t new_size)
Attempt to resize the last allocation in place.
static void update_realloc_stats (t_arena *arena, void *ptr, size_t new_size, size_t old_size, const char *label)
Update arena statistics after a successful reallocation.
Detailed Description
Internal helpers for memory allocation logic.
Function Documentation
arena_alloc_internal()
void * arena_alloc_internal (t_arena * arena, size_t size, size_t alignment, const char * label)
#include <arena_alloc.c>
Core internal allocator with alignment and labeling support.
This function performs the complete logic for allocating memory from an arena. It supports:
Alignment-aware allocation.
Out-of-bounds detection and safe growth if enabled.
Labeling for diagnostics and debugging.
Allocation hooks for instrumentation.
The flow is:
Validate input arguments (alignment, size, etc.).
Acquire the arena lock and perform consistency checks.
Ensure the arena is not being destroyed.
Check for arithmetic overflow.
Calculate aligned offset and check capacity.
Optionally grow the arena.
Commit the allocation (update offset and stats).
Zero the memory if requested via label.
Trigger the allocation hook if registered.
Return a pointer to the allocated memory.
Parameters
arena The arena from which to allocate.
size The number of bytes to allocate.
alignment The alignment in bytes (must be power of two).
label A descriptive label for logging and debugging.
Returns
A pointer to the allocated memory, or NULL on failure.
Note
Use public wrappers like arena_alloc() or arena_alloc_aligned() for convenience. This function is not meant to be called directly by users.
See also
arena_alloc
arena_alloc_aligned
arena_alloc_labeled
Definition at line 721 of file arena_alloc.c.
{
    if (!arena_alloc_validate_input(arena, size, alignment, label))
        return NULL;
    ARENA_LOCK(arena);
    ARENA_CHECK(arena);
    if (arena_is_being_destroyed(arena, label))
    {
        ARENA_UNLOCK(arena);
        return NULL;
    }
    if (arena_check_overflow(arena, size, label))
    {
        ARENA_UNLOCK(arena);
        return NULL;
    }
    size_t aligned_offset = 0;
    size_t wasted         = 0;
    if (!arena_ensure_capacity(arena, size, alignment, label, &aligned_offset, &wasted))
    {
        arena->stats.failed_allocations++;
        arena_report_error(arena, "%s failed: out of memory (requested: %zu)", label, size);
        ARENA_UNLOCK(arena);
        return NULL;
    }
    arena_commit_allocation(arena, size, wasted, aligned_offset);
    void* result = arena->buffer + aligned_offset;
    arena_zero_if_needed(result, size, label);
    arena_invoke_allocation_hook(arena, result, size, aligned_offset, wasted, label);
    ALOG("[arena] %s: Allocated %zu bytes @ offset %zu (arena %p)\n", label, size, aligned_offset, (void*) arena);
    ARENA_CHECK(arena);
    ARENA_UNLOCK(arena);
    return result;
}
References ALOG, arena_alloc_validate_input(), ARENA_CHECK, arena_check_overflow(), arena_commit_allocation(), arena_ensure_capacity(), arena_invoke_allocation_hook(), arena_is_being_destroyed(), ARENA_LOCK, arena_report_error(), ARENA_UNLOCK, and arena_zero_if_needed().
Referenced by arena_alloc(), arena_alloc_aligned(), arena_alloc_aligned_labeled(), arena_alloc_labeled(), and arena_calloc_aligned_labeled().
arena_alloc_validate_input()
static bool arena_alloc_validate_input (t_arena * arena, size_t size, size_t alignment, const char * label) inline static
#include <arena_alloc.c>
Validate input parameters for arena allocation.
This internal helper checks that all parameters passed to an arena allocation function are valid before proceeding. It performs the following checks:
The arena pointer is not NULL.
The requested size is greater than zero.
The alignment is a non-zero power of two (required for valid memory alignment).
If any of these checks fail, an appropriate error is reported using arena_report_error() with a descriptive message and the provided label.
Parameters
arena Pointer to the t_arena to validate.
size Size of the memory to allocate, in bytes.
alignment Requested alignment of the memory block (must be power-of-two).
label Name of the calling function, used in error messages.
Returns
true if all inputs are valid, false otherwise.
See also
arena_alloc_internal
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc.c.
Definition at line 311 of file arena_alloc.c.
{
    if (!arena)
    {
        arena_report_error(NULL, "%s failed: NULL arena", label);
        return false;
    }
    if (size == 0)
    {
        arena_report_error(arena, "%s failed: zero-size allocation", label);
        return false;
    }
    if (alignment == 0 || (alignment & (alignment - 1)) != 0)
    {
        arena_report_error(arena, "%s failed: alignment (%zu) is not a power-of-two", label, alignment);
        return false;
    }
    return true;
}
References arena_report_error().
Referenced by arena_alloc_internal().
arena_calc_aligned_offset()
static size_t arena_calc_aligned_offset (t_arena * arena, size_t alignment) inline static
#include <arena_alloc.c>
Compute the next aligned offset within the arena.
This helper calculates the next available offset within the arena's buffer that satisfies the specified alignment requirement. It adds the current offset to the base buffer address, rounds the result up to the nearest aligned address, and then subtracts the base address to return the aligned offset.
This value is used to ensure that allocations start at properly aligned memory locations, which is essential for performance and correctness on many platforms.
Parameters
arena Pointer to the arena structure.
alignment The desired alignment (must be a power of two).
Returns
The aligned offset (relative to the buffer base).
See also
align_up
arena_ensure_capacity
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc.c.
Definition at line 422 of file arena_alloc.c.
{
    size_t curr    = (size_t) (arena->buffer + arena->offset);
    size_t aligned = align_up(curr, alignment);
    return aligned - (size_t) arena->buffer;
}
References align_up().
Referenced by arena_ensure_capacity().
arena_check_overflow()
static bool arena_check_overflow (t_arena * arena, size_t size, const char * label) inline static
#include <arena_alloc.c>
Check whether an allocation would cause a size_t overflow.
This helper ensures that the requested allocation does not exceed the bounds of the addressable memory space by checking for integer overflow when adding size to the current arena->offset.
If an overflow would occur, the function:
Increments the failed_allocations counter in the arena stats.
Logs an error message with the given label.
Returns true to indicate failure.
Parameters
arena Pointer to the arena being used for allocation.
size The requested allocation size in bytes.
label Label or name of the calling function for error context.
Returns
true if an overflow would occur, false otherwise.
See also
arena_alloc_internal
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc.c.
Definition at line 388 of file arena_alloc.c.
{
    if (size > SIZE_MAX - arena->offset)
    {
        arena->stats.failed_allocations++;
        arena_report_error(arena, "%s failed: size overflow (requested: %zu)", label, size);
        return true;
    }
    return false;
}
References arena_report_error().
Referenced by arena_alloc_internal().
arena_commit_allocation()
static void arena_commit_allocation (t_arena * arena, size_t size, size_t wasted, size_t aligned_offset) inline static
#include <arena_alloc.c>
Update offset, peak usage, and statistics.
This internal helper is used after determining that an allocation can safely be performed. It updates the arena's offset to reflect the new allocation, invokes arena_update_peak() to track maximum usage, and updates internal statistics such as allocation count, total allocated bytes, and alignment waste via arena_update_stats().
Parameters
arena Pointer to the arena being updated.
size Size in bytes of the allocation.
wasted Number of alignment bytes wasted.
aligned_offset Offset where the allocation begins in the buffer.
Note
This function assumes that allocation boundaries and capacity have already been validated via arena_ensure_capacity().
See also
arena_alloc_internal
arena_update_stats
arena_update_peak
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc.c.
Definition at line 593 of file arena_alloc.c.
{
    arena->offset = aligned_offset + size;
    arena_update_peak(arena);
    arena_update_stats(arena, size, wasted);
}
References arena_update_peak(), and arena_update_stats().
Referenced by arena_alloc_internal().
arena_ensure_capacity()
static bool arena_ensure_capacity (t_arena * arena, size_t size, size_t alignment, const char * label, size_t * aligned_offset, size_t * wasted) inline static
#include <arena_alloc.c>
Ensure that the arena has enough space for a new allocation with alignment.
This function calculates the aligned offset needed to satisfy an allocation of size bytes with the given alignment. If the allocation fits in the current arena buffer, the function returns true.
If the buffer is too small and the arena is allowed to grow, it attempts to expand the buffer via arena_try_grow(), and then recalculates the offset and checks again.
This function returns:
true if enough space is available (after optional growth).
false if the arena cannot grow or is still too small.
The final aligned offset and wasted bytes (padding due to alignment) are written to the provided output pointers.
Parameters
arena Pointer to the arena being used.
size Size of the requested allocation (in bytes).
alignment Required alignment (must be power-of-two).
label Label for logging and error reporting.
aligned_offset Output: aligned offset where the allocation would start.
wasted Output: number of bytes wasted due to alignment padding.
Returns
true if capacity is sufficient, false otherwise.
See also
arena_calc_aligned_offset
arena_try_grow
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc.c.
Definition at line 503 of file arena_alloc.c.
{
    *aligned_offset = arena_calc_aligned_offset(arena, alignment);
    *wasted         = *aligned_offset - arena->offset;
    if (*aligned_offset + size <= arena->size)
        return true;
    if (!arena_try_grow(arena, size, label))
        return false;
    *aligned_offset = arena_calc_aligned_offset(arena, alignment);
    *wasted         = *aligned_offset - arena->offset;
    return *aligned_offset + size <= arena->size;
}
References arena_calc_aligned_offset(), and arena_try_grow().
Referenced by arena_alloc_internal().
arena_invoke_allocation_hook()
static void arena_invoke_allocation_hook (t_arena * arena, void * ptr, size_t size, size_t offset, size_t wasted, const char * label) inline static
#include <arena_alloc.c>
Invoke the user-defined allocation hook, if registered.
This internal utility checks whether an allocation hook has been registered in the arenas debug hook system (arena->hooks.hook_cb). If a hook is set, it is called with detailed allocation metadata:
Arena pointer
Allocation ID
Pointer to the allocated memory
Size of the allocation
Offset in the arena buffer
Wasted bytes due to alignment
Allocation label
The hook is loaded using atomic_load_explicit to ensure safe concurrent access. This mechanism enables advanced users to track allocations (e.g., for profiling, leak detection, or debugging).
Parameters
arena Pointer to the arena that performed the allocation.
ptr Pointer to the allocated memory block.
size Number of bytes allocated.
offset Offset in the arena buffer where the allocation began.
wasted Number of wasted bytes due to alignment padding.
label Label associated with this allocation.
Note
If no hook is set, this function does nothing.
See also
arena_set_allocation_hook
arena_alloc_internal
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc.c.
Definition at line 672 of file arena_alloc.c.
{
    arena_allocation_hook hook = atomic_load_explicit(&arena->hooks.hook_cb, memory_order_acquire);
    if (hook)
        hook(arena, (int) arena->stats.alloc_id_counter, ptr, size, offset, wasted, label);
}
Referenced by arena_alloc_internal().
arena_is_being_destroyed()
static bool arena_is_being_destroyed (t_arena * arena, const char * label) inline static
#include <arena_alloc.c>
Check whether the arena is currently being destroyed.
This internal helper inspects the is_destroying atomic flag to determine whether the arena is in the process of being torn down (e.g., via arena_destroy()).
If the flag is set, an error is reported with the provided label, and the function returns true to indicate that no further operations should be performed on the arena.
This check prevents undefined behavior and race conditions by avoiding memory access or mutation while destruction is in progress.
Parameters
arena Pointer to the arena being queried.
label Name of the calling function, used for contextual error messages.
Returns
true if the arena is being destroyed, false otherwise.
See also
arena_destroy
arena_alloc_internal
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc.c.
Definition at line 356 of file arena_alloc.c.
{
    (void)label;
    if (atomic_load_explicit(&arena->is_destroying, memory_order_acquire))
        return true;
    return false;
}
Referenced by arena_alloc_internal().
arena_realloc_validate()
static bool arena_realloc_validate (t_arena * arena, void * old_ptr, size_t new_size) inline static
#include <arena_realloc_last.c>
Validate input arguments for arena_realloc_last.
This internal helper checks that the inputs to arena_realloc_last are valid before proceeding with reallocation logic. It ensures:
The arena pointer is not NULL.
The old_ptr is not NULL.
The new_size is greater than zero.
If any check fails, a descriptive error is reported using arena_report_error().
Parameters
arena Pointer to the arena where the reallocation is performed.
old_ptr Pointer to the previously allocated memory.
new_size New size requested for the reallocation (in bytes).
Returns
true if inputs are valid, false otherwise.
See also
arena_realloc_last
arena_report_error
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_realloc_last.c.
Definition at line 167 of file arena_realloc_last.c.
{
    if (!arena)
        return arena_report_error(NULL, "arena_realloc_last failed: NULL arena"), false;
    if (!old_ptr)
        return arena_report_error(arena, "arena_realloc_last failed: NULL old_ptr"), false;
    if (new_size == 0)
        return arena_report_error(arena, "arena_realloc_last failed: zero-size reallocation"), false;
    return true;
}
References arena_report_error().
Referenced by arena_realloc_last().
arena_try_grow()
static bool arena_try_grow (t_arena * arena, size_t size, const char * label) inline static
#include <arena_alloc.c>
Attempt to grow the arena's buffer to satisfy an upcoming allocation.
This internal helper checks whether the arena is allowed to grow (can_grow flag) and, if so, attempts to expand its memory region by calling arena_grow().
If growth is disallowed or fails, an appropriate error is reported with the given label for context, and the function returns false.
This function helps support dynamic allocation models where the arena is allowed to resize its memory buffer when out of space.
Parameters
arena Pointer to the arena to grow.
size Minimum number of bytes required to satisfy the next allocation.
label Allocation label used for context in error messages.
Returns
true if growth succeeded or was unnecessary, false otherwise.
See also
arena_grow
arena_ensure_capacity
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc.c.
Definition at line 454 of file arena_alloc.c.
{
    if (!arena->can_grow)
    {
        arena_report_error(arena, "%s failed: cannot grow", label);
        return false;
    }
    if (!arena_grow(arena, size))
    {
        arena_report_error(arena, "%s failed: growth failed", label);
        return false;
    }
    return true;
}
References arena_grow(), and arena_report_error().
Referenced by arena_ensure_capacity().
arena_update_stats()
static void arena_update_stats (t_arena * arena, size_t size, size_t wasted) inline static
#include <arena_alloc.c>
Update allocation statistics after a successful arena allocation.
This function increments and records key allocation-related statistics inside the arena->stats structure. These statistics include:
Total number of allocations (allocations)
Current number of live allocations (live_allocations)
Total number of bytes allocated (bytes_allocated)
Total number of wasted bytes due to alignment (wasted_alignment_bytes)
Last allocation size (last_alloc_size)
Offset of the last allocation (last_alloc_offset)
Allocation ID counter (alloc_id_counter)
The stats are updated inside a critical section to ensure thread safety when ARENA_ENABLE_THREAD_SAFE is enabled.
Parameters
arena Pointer to the arena whose statistics are to be updated.
size Number of bytes allocated.
wasted Number of bytes wasted due to alignment padding.
Note
This function performs locking internally (via ARENA_LOCK / ARENA_UNLOCK), so it should not be called within an existing locked section to avoid deadlocks.
See also
arena_commit_allocation
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc.c.
Definition at line 551 of file arena_alloc.c.
{
    if (!arena)
        return;
    ARENA_LOCK(arena);
    arena->stats.allocations++;
    arena->stats.live_allocations++;
    arena->stats.bytes_allocated += size;
    arena->stats.wasted_alignment_bytes += wasted;
    arena->stats.alloc_id_counter++;
    arena->stats.last_alloc_size   = size;
    arena->stats.last_alloc_offset = arena->offset - size;
    ARENA_UNLOCK(arena);
}
References ARENA_LOCK, and ARENA_UNLOCK.
Referenced by arena_commit_allocation().
arena_zero_if_needed()
static void arena_zero_if_needed (void * ptr, size_t size, const char * label) inline static
#include <arena_alloc.c>
Zero or poison a memory region depending on allocation label.
This internal utility determines whether a newly allocated block of memory should be zero-initialized or poisoned for debugging purposes.
If the provided label is exactly "arena_calloc_zero", the memory is cleared using memset(ptr, 0, size). Otherwise, the memory is poisoned using arena_poison_memory() to help detect uninitialized access in debugging mode.
This is typically used in arena_alloc_internal() after computing the memory location of a new allocation.
Parameters
ptr Pointer to the memory block to initialize.
size Number of bytes to initialize.
label Allocation label string used to determine behavior.
Note
The label comparison is string-based; other labels will trigger poisoning in debug mode.
See also
arena_alloc_internal
arena_poison_memory
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc.c.
Definition at line 628 of file arena_alloc.c.
{
    if (label && strcmp(label, "arena_calloc_zero") == 0)
        memset(ptr, 0, size);
    else
        arena_poison_memory(ptr, size);
}
References arena_poison_memory.
Referenced by arena_alloc_internal().
is_last_allocation()
static bool is_last_allocation (t_arena * arena, void * old_ptr, size_t old_size) inline static
#include <arena_realloc_last.c>
Check if a given pointer corresponds to the most recent allocation.
This helper determines whether old_ptr is the last allocation made by the arena. It does so by comparing the pointer to the expected end of the buffer based on arena->offset and the known old_size.
This check is necessary before attempting an in-place reallocation, as only the last allocation can be safely resized in place.
Parameters
arena Pointer to the arena.
old_ptr Pointer to the memory block to check.
old_size Size of the previously allocated memory block.
Returns
true if old_ptr is the last allocation, false otherwise.
See also
arena_realloc_last
realloc_in_place
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_realloc_last.c.
Definition at line 201 of file arena_realloc_last.c.
{
    uint8_t* expected = arena->buffer + (arena->offset - old_size);
    return (uint8_t*) old_ptr == expected;
}
Referenced by arena_realloc_last().
realloc_fallback()
static void * realloc_fallback (t_arena * arena, void * old_ptr, size_t old_size, size_t new_size) inline static
#include <arena_realloc_last.c>
Perform a fallback reallocation by allocating new memory and copying data.
This internal function is used when arena_realloc_last() cannot perform an in-place reallocation (e.g., when the old pointer is not the last allocation).
It performs the following steps:
Allocates a new memory block of new_size bytes.
Copies min(old_size, new_size) bytes from the old block to the new block.
Poisons the old memory region for debugging purposes.
Updates internal reallocation statistics and invokes the allocation hook, if set.
This approach ensures consistent tracking of memory usage even when in-place reallocation is not possible.
Parameters
arena Pointer to the arena from which to allocate new memory.
old_ptr Pointer to the original memory block.
old_size Size of the original allocation.
new_size Desired size of the new allocation.
Returns
Pointer to the newly allocated memory block, or NULL on failure.
See also
arena_realloc_last
realloc_in_place
update_realloc_stats
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_realloc_last.c.
Definition at line 330 of file arena_realloc_last.c.
{
    void* new_ptr = arena_alloc(arena, new_size);
    if (!new_ptr)
        return NULL;
    memcpy(new_ptr, old_ptr, old_size < new_size ? old_size : new_size);
    ARENA_LOCK(arena);
    arena_poison_memory(old_ptr, old_size);
    ARENA_UNLOCK(arena);
    update_realloc_stats(arena, new_ptr, new_size, old_size, "arena_realloc_last (fallback)");
    return new_ptr;
}
References arena_alloc(), ARENA_LOCK, arena_poison_memory, ARENA_UNLOCK, and update_realloc_stats().
Referenced by arena_realloc_last().
realloc_in_place()
static void * realloc_in_place (t_arena * arena, void * old_ptr, size_t old_size, size_t new_size) inline static
#include <arena_realloc_last.c>
Attempt to resize the last allocation in place.
This internal function resizes the most recent allocation made by the arena, assuming that old_ptr points to the last allocated block.
If the new size extends beyond the current buffer capacity, it attempts to grow the arena using arena_grow(). If growth fails, the function reports an error and returns NULL.
If the new size is smaller than the original, the unused tail of the allocation is poisoned to help catch accidental use of stale memory in debug mode.
The function updates internal statistics and triggers the allocation hook with the "arena_realloc_last (in-place)" label to reflect the successful resize.
Parameters
arena Pointer to the arena managing the memory.
old_ptr Pointer to the memory block being reallocated.
old_size Size of the current allocation in bytes.
new_size Desired new size in bytes.
Returns
old_ptr if the resize succeeded in place, or NULL on failure.
See also
arena_grow
update_realloc_stats
arena_realloc_last
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_realloc_last.c.
Definition at line 284 of file arena_realloc_last.c.
{
    size_t new_end = arena->offset - old_size + new_size;
    if (new_end > arena->size && !arena_grow(arena, new_size - old_size))
        return arena_report_error(arena, "arena_realloc_last failed: growth failed (needed %zu bytes)",
                                  new_size - old_size),
               NULL;
    if (new_size < old_size)
        arena_poison_memory((uint8_t*) old_ptr + new_size, old_size - new_size);
    update_realloc_stats(arena, old_ptr, new_size, old_size, "arena_realloc_last (in-place)");
    return old_ptr;
}
References arena_grow(), arena_poison_memory, arena_report_error(), and update_realloc_stats().
Referenced by arena_realloc_last().
update_realloc_stats()
static void update_realloc_stats (t_arena * arena, void * ptr, size_t new_size, size_t old_size, const char * label) inline static
#include <arena_realloc_last.c>
Update arena statistics after a successful reallocation.
This internal helper updates the arena's internal state to reflect a successful in-place reallocation. It performs the following:
Adjusts the offset to account for the new allocation size.
Updates peak usage via arena_update_peak().
Increments allocation-related counters.
Records metadata about the last allocation (size, offset).
Triggers the allocation hook if one is registered.
This function is used exclusively during in-place reallocation, where the existing memory block remains valid and grows or shrinks.
Parameters
arena Pointer to the arena being updated.
ptr Pointer to the reallocated memory block.
new_size New size of the allocation (in bytes).
old_size Previous size of the allocation (in bytes).
label Descriptive label for logging and tracking.
See also
realloc_in_place
realloc_fallback
arena_realloc_last
arena_update_peak
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_realloc_last.c.
Definition at line 236 of file arena_realloc_last.c.
{
    arena->offset = (uint8_t*) ptr + new_size - arena->buffer;
    arena_update_peak(arena);
    arena->stats.reallocations++;
    arena->stats.live_allocations++;
    arena->stats.bytes_allocated += (new_size - old_size);
    arena->stats.last_alloc_size   = new_size;
    arena->stats.last_alloc_offset = (size_t) ((uint8_t*) ptr - arena->buffer);
    arena->stats.alloc_id_counter++;
    if (arena->hooks.hook_cb)
        arena->hooks.hook_cb(arena, (int) arena->stats.alloc_id_counter, ptr, new_size, arena->stats.last_alloc_offset,
                             0, label);
}
References arena_update_peak().
Referenced by realloc_fallback(), and realloc_in_place().