memory_arena: Scratch Arena Pool
Scratch Arena Pool
Public API for acquiring and releasing temporary memory arenas from a pool.
Files
file arena_scratch.c
Implementation of scratch arena pool system for temporary, fast, and reusable allocations.
file arena_scratch.h
Scratch arena pool system for fast, reusable temporary allocations.
Data Structures
struct s_scratch_arena_pool
Scratch arena pool structure holding multiple reusable memory arenas.
Typedefs
typedef struct s_scratch_arena_pool t_scratch_arena_pool
Scratch arena pool structure holding multiple reusable memory arenas.
Functions
t_arena * scratch_acquire (t_scratch_arena_pool *pool)
Acquire a temporary scratch arena from the pool.
void scratch_pool_destroy (t_scratch_arena_pool *pool)
Destroy all arenas in a scratch pool and reset its metadata.
bool scratch_pool_init (t_scratch_arena_pool *pool, size_t slot_size, bool thread_safe)
Initialize a scratch arena pool with pre-allocated slots.
void scratch_release (t_scratch_arena_pool *pool, t_arena *arena)
Release a scratch arena back to the pool for reuse.
Detailed Description
Public API for acquiring and releasing temporary memory arenas from a pool.
Scratch arenas are useful for high-frequency temporary allocations in performance-critical paths. These APIs support fast, reusable memory arenas from a preallocated pool with optional thread safety.
Data Structure Documentation
s_scratch_arena_pool
struct s_scratch_arena_pool
Scratch arena pool structure holding multiple reusable memory arenas.
This structure maintains a fixed number of scratch slots that can be individually acquired and reset for temporary memory needs.
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/arena_scratch.c.
Definition at line 89 of file arena_scratch.h.
Data Fields
pthread_mutex_t lock
Mutex for protecting slot access.
size_t slot_size
Size of each arena in bytes.
t_scratch_slot slots [SCRATCH_MAX_SLOTS]
Array of scratch slots.
bool thread_safe
Whether locking is enabled.
Field Documentation
lock
pthread_mutex_t s_scratch_arena_pool::lock
Mutex for protecting slot access.
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/arena_scratch.c.
Definition at line 94 of file arena_scratch.h.
Referenced by scratch_pool_destroy(), and scratch_pool_init().
slot_size
size_t s_scratch_arena_pool::slot_size
Size of each arena in bytes.
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/arena_scratch.c.
Definition at line 92 of file arena_scratch.h.
Referenced by scratch_pool_init().
slots
t_scratch_slot s_scratch_arena_pool::slots[SCRATCH_MAX_SLOTS]
Array of scratch slots.
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/arena_scratch.c.
Definition at line 91 of file arena_scratch.h.
Referenced by scratch_acquire(), scratch_pool_destroy(), scratch_pool_init(), and scratch_release().
thread_safe
bool s_scratch_arena_pool::thread_safe
Whether locking is enabled.
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/arena_scratch.c.
Definition at line 93 of file arena_scratch.h.
Referenced by scratch_pool_destroy(), and scratch_pool_init().
Typedef Documentation
t_scratch_arena_pool
typedef struct s_scratch_arena_pool t_scratch_arena_pool
#include <arena_scratch.h>
Scratch arena pool structure holding multiple reusable memory arenas.
This structure maintains a fixed number of scratch slots that can be individually acquired and reset for temporary memory needs.
Function Documentation
scratch_acquire()
t_arena * scratch_acquire (t_scratch_arena_pool * pool)
#include <arena_scratch.h>
Acquire a temporary scratch arena from the pool.
This function returns a pointer to a scratch arena from the given pool that is currently available (i.e., not in use). Internally, it scans the pool’s slots and uses an atomic flag to claim one safely, even in multithreaded contexts.
Upon successful acquisition:
The arena is marked as in-use via atomic_exchange().
Its memory is cleared using arena_reset() before returning.
If no arenas are available, the function returns NULL and reports an error. This may happen when all slots are concurrently in use or exhausted.
Parameters
pool Pointer to the scratch arena pool to acquire from.
Returns
Pointer to a t_arena if one is available, or NULL on failure.
Note
The returned arena must be released using scratch_release() when no longer needed.
Warning
The arena is not thread-safe by default. Do not use the same scratch slot concurrently without external synchronization.
See also
scratch_release
arena_reset
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/arena_scratch.c.
Definition at line 350 of file arena_scratch.c.
{
    if (!pool)
        return arena_report_error(NULL, "scratch_acquire failed: pool is NULL"), NULL;
    SCRATCH_LOCK(pool);
    for (int i = 0; i < SCRATCH_MAX_SLOTS; ++i)
    {
        if (!atomic_exchange(&pool->slots[i].in_use, true))
        {
            arena_reset(&pool->slots[i].arena);
            SCRATCH_UNLOCK(pool);
            return &pool->slots[i].arena;
        }
    }
    SCRATCH_UNLOCK(pool);
    return arena_report_error(NULL, "scratch_acquire failed: all slots in use"), NULL;
}
References s_scratch_slot::arena, arena_report_error(), arena_reset(), s_scratch_slot::in_use, SCRATCH_LOCK, SCRATCH_MAX_SLOTS, SCRATCH_UNLOCK, and s_scratch_arena_pool::slots.
scratch_pool_destroy()
void scratch_pool_destroy (t_scratch_arena_pool * pool)
#include <arena_scratch.h>
Destroy all arenas in a scratch pool and reset its metadata.
This function deinitializes all scratch arenas in the pool by calling arena_destroy() on each slot. If the pool was initialized as thread-safe, it also destroys the associated mutex.
After cleanup, the pool's memory is zeroed out using memset to prevent accidental reuse or access to invalidated arenas.
This function must be called before deallocating or discarding a scratch pool, especially in cases where initialization (scratch_pool_init) succeeded only partially or the pool is no longer needed.
Parameters
pool Pointer to the scratch arena pool to destroy.
Returns
void
Note
This function is idempotent: calling it on a NULL pool is safe and has no effect.
See also
scratch_pool_init
arena_destroy
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/arena_scratch.c.
Definition at line 302 of file arena_scratch.c.
{
    if (!pool)
        return;
    for (int i = 0; i < SCRATCH_MAX_SLOTS; ++i)
        arena_destroy(&pool->slots[i].arena);
#ifdef ARENA_ENABLE_THREAD_SAFE
    if (pool->thread_safe)
        pthread_mutex_destroy(&pool->lock);
#endif
    memset(pool, 0, sizeof(*pool));
}
References s_scratch_slot::arena, arena_destroy(), s_scratch_arena_pool::lock, SCRATCH_MAX_SLOTS, s_scratch_arena_pool::slots, and s_scratch_arena_pool::thread_safe.
Referenced by scratch_pool_init().
scratch_pool_init()
bool scratch_pool_init (t_scratch_arena_pool * pool, size_t slot_size, bool thread_safe)
#include <arena_scratch.h>
Initialize a scratch arena pool with pre-allocated slots.
This function sets up a reusable pool of scratch arenas, each initialized to the same slot_size. It prepares the internal array of slots, resets metadata, and (if enabled) configures a mutex for thread safety.
For each slot:
An arena is initialized with the specified slot_size.
The slot is marked as not in use.
If any arena initialization fails, the entire pool is destroyed via scratch_pool_destroy() and the function returns false.
Parameters
pool Pointer to the scratch pool structure to initialize.
slot_size Size of each individual scratch arena (in bytes).
thread_safe If true, enables mutex-based locking for slot access.
Returns
true if the pool was successfully initialized, false otherwise.
Note
All arenas in the pool are marked as growable by default.
Warning
You must call scratch_pool_destroy() to clean up the pool before deallocating it.
See also
scratch_slot_init
scratch_pool_destroy
scratch_acquire
scratch_release
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/arena_scratch.c.
Definition at line 249 of file arena_scratch.c.
{
    if (!pool || slot_size == 0)
        return arena_report_error(NULL, "scratch_pool_init failed: invalid arguments"), false;
    memset(pool, 0, sizeof(*pool));
    pool->slot_size   = slot_size;
    pool->thread_safe = thread_safe;
#ifdef ARENA_ENABLE_THREAD_SAFE
    if (thread_safe)
        pthread_mutex_init(&pool->lock, NULL);
#endif
    for (int i = 0; i < SCRATCH_MAX_SLOTS; ++i)
    {
        if (!scratch_slot_init(&pool->slots[i], slot_size, i))
        {
            scratch_pool_destroy(pool);
            return false;
        }
    }
    return true;
}
References arena_report_error(), s_scratch_arena_pool::lock, SCRATCH_MAX_SLOTS, scratch_pool_destroy(), scratch_slot_init(), s_scratch_arena_pool::slot_size, s_scratch_arena_pool::slots, and s_scratch_arena_pool::thread_safe.
scratch_release()
void scratch_release (t_scratch_arena_pool * pool, t_arena * arena)
#include <arena_scratch.h>
Release a scratch arena back to the pool for reuse.
This function marks a previously acquired scratch arena as available again. It searches the pool’s slots for a match with the provided arena pointer, and clears the in_use flag using atomic_store().
This allows the arena to be reused by future calls to scratch_acquire().
If the provided arena does not match any slot in the pool, the function logs an error via arena_report_error() and does nothing.
Parameters
pool Pointer to the scratch pool the arena belongs to.
arena Pointer to the arena to release.
Note
It is safe to call this function multiple times with the same arena, but doing so without matching scratch_acquire() calls may cause logic errors.
Warning
The arena must have been obtained from the same pool via scratch_acquire(). Passing an invalid or mismatched pointer results in an error.
See also
scratch_acquire
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/arena_scratch.c.
Definition at line 398 of file arena_scratch.c.
{
    if (!pool || !arena)
    {
        arena_report_error(NULL, "scratch_release failed: null pool or arena");
        return;
    }
    for (int i = 0; i < SCRATCH_MAX_SLOTS; ++i)
    {
        if (&pool->slots[i].arena == arena)
        {
            atomic_store(&pool->slots[i].in_use, false);
            return;
        }
    }
    arena_report_error(arena, "scratch_release failed: arena not found in pool");
}
References s_scratch_slot::arena, arena_report_error(), s_scratch_slot::in_use, SCRATCH_MAX_SLOTS, and s_scratch_arena_pool::slots.