memory_arena: Arena Resize Internals
Arena Resize Internals
Internal Implementation
Internal helpers for growing and shrinking memory buffers.
Functions
static bool arena_can_shrink (t_arena *arena, size_t new_size)
Determine whether the arena is eligible for shrinking to a smaller size.
static size_t arena_grow_compute_new_size (t_arena *arena, size_t required_size)
Compute the new size for the arena based on the growth policy.
static bool arena_grow_realloc_buffer (t_arena *arena, size_t new_size, size_t old_size)
Reallocate the arena's buffer to a new size.
static bool arena_grow_validate (t_arena *arena, size_t required_size)
Validate whether the arena is allowed to grow for a given request.
static void arena_record_growth (t_arena *arena, size_t old_size)
Record the previous size of the arena in the growth history.
static bool arena_should_grow (const t_arena *arena)
Check whether the arena is allowed to grow.
static bool arena_should_maybe_shrink (size_t used, size_t size)
Decide whether the arena buffer should be shrunk based on usage ratio.
static bool arena_shrink_apply (t_arena *arena, size_t new_size)
Apply the memory shrink operation to an arena's buffer.
static size_t arena_shrink_target (size_t used)
Compute the target buffer size for a shrink operation.
static bool arena_shrink_validate (t_arena *arena, size_t new_size)
Validate whether an arena can be safely shrunk to a new size.
static bool should_attempt_shrink (t_arena *arena)
Determine whether the arena is eligible for dynamic shrinking.
Detailed Description
Internal helpers for growing and shrinking memory buffers.
Function Documentation
arena_can_shrink()
static bool arena_can_shrink (t_arena * arena, size_t new_size) inline static
#include <arena_resize.c>
Determine whether the arena is eligible for shrinking to a smaller size.
This internal helper checks if the arena can be safely shrunk to new_size based on ownership, growth policy, and current memory usage.
Shrinking is allowed only if:
The arena is not NULL.
The arena owns its buffer and is allowed to grow/shrink.
The proposed new_size is not smaller than the current offset.
The ratio of new_size / current_size is less than or equal to the configured threshold (ARENA_MIN_SHRINK_RATIO), unless it matches the offset.
This function is used as a precondition check before applying memory reduction via arena_shrink().
Parameters
arena Pointer to the t_arena instance.
new_size Proposed size for shrinking the buffer.
Returns
true if the arena is eligible to shrink, false otherwise.
Note
If new_size == arena->offset, shrinking is always allowed (tight fit).
See also
arena_shrink
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/arena_resize.c.
Definition at line 639 of file arena_resize.c.
{
    if (!arena)
        return false;
    bool owns = atomic_load_explicit(&arena->owns_buffer, memory_order_acquire);
    bool grow = atomic_load_explicit(&arena->can_grow, memory_order_acquire);
    if (!owns || !grow)
        return false;
    if (new_size < arena->offset)
        return false;
    if (new_size == arena->offset)
        return true;
    double shrink_ratio = (double) new_size / (double) arena->size;
    return shrink_ratio <= ARENA_MIN_SHRINK_RATIO;
}
References ARENA_MIN_SHRINK_RATIO.
Referenced by arena_shrink_validate().
arena_grow_compute_new_size()
static size_t arena_grow_compute_new_size (t_arena * arena, size_t required_size) inline static
#include <arena_resize.c>
Compute the new size for the arena based on the growth policy.
This internal function calculates an appropriate new buffer size that satisfies the required_size request, starting from the current size and offset. It uses the user-defined growth callback if set, or defaults to default_grow_cb otherwise.
The result is validated to ensure it is:
Large enough to satisfy the requested offset + size.
Not exceeding SIZE_MAX.
If the computed size is invalid (too small or overflowing), the function returns 0 to indicate failure.
Parameters
arena Pointer to the arena requesting growth.
required_size The number of additional bytes needed.
Returns
The computed new size in bytes, or 0 if the value is invalid.
See also
arena_grow
arena_grow_validate
arena_grow_callback
default_grow_cb
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/arena_resize.c.
Definition at line 552 of file arena_resize.c.
{
    arena_grow_callback cb        = arena->grow_cb ? arena->grow_cb : default_grow_cb;
    size_t              requested = arena->offset + required_size;
    size_t              new_size  = cb(arena->size, required_size);
    if (new_size < requested)
        return 0;
    if (new_size > SIZE_MAX)
        return 0;
    return new_size;
}
References default_grow_cb().
Referenced by arena_grow().
arena_grow_realloc_buffer()
static bool arena_grow_realloc_buffer (t_arena * arena, size_t new_size, size_t old_size) inline static
#include <arena_resize.c>
Reallocate the arena's buffer to a new size.
This internal function performs the actual realloc() of the arena's buffer during a grow operation. It attempts to allocate a new buffer of new_size bytes, and if successful:
Updates the buffer pointer and size.
Increments the reallocation counter.
Records the previous size in the arena's growth history.
Emits a debug log message indicating the resize.
If reallocation fails, an error is reported and false is returned.
Parameters
arena Pointer to the arena being resized.
new_size Target buffer size after reallocation (in bytes).
old_size Original size of the buffer before reallocation.
Returns
true if reallocation succeeded, false otherwise.
See also
arena_grow
arena_record_growth
realloc
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/arena_resize.c.
Definition at line 593 of file arena_resize.c.
{
    void* new_buf = realloc(arena->buffer, new_size);
    if (!new_buf)
        return arena_report_error(arena, "arena_grow failed: realloc failed"), false;
    arena->buffer = (uint8_t*) new_buf;
    arena->size   = new_size;
    arena->stats.reallocations++;
    arena_record_growth(arena, old_size);
    ALOG("[arena_grow] Arena %p grown from %zu to %zu bytes\n", (void*) arena, old_size, new_size);
    return true;
}
References ALOG, arena_record_growth(), and arena_report_error().
Referenced by arena_grow().
arena_grow_validate()
static bool arena_grow_validate (t_arena * arena, size_t required_size) inline static
#include <arena_resize.c>
Validate whether the arena is allowed to grow for a given request.
This internal helper checks if the arena meets the conditions necessary to perform a growth operation. It verifies:
That the arena is marked as growable (can_grow == true).
That the arena owns its buffer (owns_buffer == true).
That the requested growth does not overflow size_t when added to the current offset.
If any condition fails, an error is reported using arena_report_error() and the function returns false.
Parameters
arena Pointer to the arena to validate.
required_size The number of additional bytes needed.
Returns
true if the arena is eligible for growth, false otherwise.
Note
This function is called from within a section where the arena is already locked for thread safety.
See also
arena_grow
arena_should_grow
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/arena_resize.c.
Definition at line 512 of file arena_resize.c.
{
    if (!arena_should_grow(arena))
        return arena_report_error(arena, "arena_grow failed: growth not allowed"), false;
    if (required_size > SIZE_MAX - arena->offset)
        return arena_report_error(arena, "arena_grow failed: size overflow"), false;
    return true;
}
References arena_report_error(), and arena_should_grow().
Referenced by arena_grow().
arena_record_growth()
static void arena_record_growth (t_arena * arena, size_t old_size) inline static
#include <arena_resize.c>
Record the previous size of the arena in the growth history.
This internal helper appends the old_size of the arena to its growth_history array. This array keeps track of all prior sizes before each successful call to arena_grow(), allowing for optional introspection, debugging, or visualization of growth patterns.
It reallocates the history buffer with enough room for the new entry. If realloc fails, the history is not updated, but the function fails silently to avoid interrupting allocation logic.
Parameters
arena Pointer to the arena whose growth is being tracked.
old_size The size of the arena before a successful growth.
Note
This function is called from within a section that already holds the arena lock.
See also
arena_grow
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/arena_resize.c.
Definition at line 472 of file arena_resize.c.
{
    size_t* temp = realloc(arena->stats.growth_history, sizeof(size_t) * (arena->stats.growth_history_count + 1));
    if (temp)
    {
        arena->stats.growth_history                                      = temp;
        arena->stats.growth_history[arena->stats.growth_history_count++] = old_size;
    }
}
Referenced by arena_grow_realloc_buffer().
arena_should_grow()
static bool arena_should_grow (const t_arena * arena) inline static
#include <arena_resize.c>
Check whether the arena is allowed to grow.
This internal helper verifies if the arena is configured to support dynamic growth. It performs the following checks:
The arena must own its memory buffer (owns_buffer == true).
The arena must have growth enabled (can_grow == true).
If both conditions are met, the arena can attempt to grow when additional memory is needed.
Parameters
arena Pointer to the t_arena structure.
Returns
true if the arena can grow, false otherwise.
Note
This function assumes arena is non-NULL. It is called by a function that validates the pointer before calling.
See also
arena_grow
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/arena_resize.c.
Definition at line 440 of file arena_resize.c.
{
    bool owns = atomic_load_explicit(&arena->owns_buffer, memory_order_acquire);
    bool grow = atomic_load_explicit(&arena->can_grow, memory_order_acquire);
    return owns && grow;
}
Referenced by arena_grow_validate().
arena_should_maybe_shrink()
static bool arena_should_maybe_shrink (size_t used, size_t size) inline static
#include <arena_resize.c>
Decide whether the arena buffer should be shrunk based on usage ratio.
This helper compares the ratio of used bytes to total allocated buffer size. If the usage ratio falls below ARENA_MIN_SHRINK_RATIO, the arena is considered underutilized and may be eligible for shrinking.
Typical usage scenarios include:
Periodic memory trimming in long-running programs.
Adaptive memory management after large but short-lived allocations.
Parameters
used Number of bytes currently used in the arena.
size Total capacity of the arena buffer.
Returns
true if the usage is low enough to consider shrinking, false otherwise.
Note
If size is 0, this function returns false to avoid division-by-zero.
See also
arena_might_shrink
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/arena_resize.c.
Definition at line 787 of file arena_resize.c.
{
    if (size == 0)
        return false;
    double ratio = (double) used / (double) size;
    return ratio < ARENA_MIN_SHRINK_RATIO;
}
References ARENA_MIN_SHRINK_RATIO, and used.
Referenced by arena_might_shrink().
arena_shrink_apply()
static bool arena_shrink_apply (t_arena * arena, size_t new_size) inline static
#include <arena_resize.c>
Apply the memory shrink operation to an arena's buffer.
This internal function performs the actual memory reallocation to reduce the arena's backing buffer to new_size bytes.
On success:
The arena's buffer pointer and size field are updated.
The shrinks counter in arena statistics is incremented.
A debug log message is printed.
If realloc() fails, the arena remains unchanged and the function returns false.
Parameters
arena Pointer to the arena to shrink.
new_size New desired size of the arena buffer (in bytes).
Returns
true on successful shrink, false on failure.
Note
This function is only called after validating the shrink operation.
See also
arena_can_shrink
arena_shrink
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/arena_resize.c.
Definition at line 719 of file arena_resize.c.
{
    void* new_buf = realloc(arena->buffer, new_size);
    if (!new_buf)
        return false;
    arena->buffer = (uint8_t*) new_buf;
    arena->size   = new_size;
    arena->stats.shrinks++;
    ALOG("[arena_shrink] Arena %p shrunk to %zu bytes\n", (void*) arena, new_size);
    return true;
}
References ALOG.
Referenced by arena_shrink().
arena_shrink_target()
static size_t arena_shrink_target (size_t used) inline static
#include <arena_resize.c>
Compute the target buffer size for a shrink operation.
This helper calculates a reasonable new size for the arena buffer when shrinking is considered. It adds a small safety margin (ARENA_SHRINK_PADDING) to the current usage (used) to avoid immediate re-growth if a small allocation occurs after shrinking.
The padding ensures that the buffer remains slightly larger than strictly needed, providing better performance and avoiding fragmentation.
Parameters
used Number of bytes currently used in the arena.
Returns
Suggested new size for the buffer after shrinking.
See also
arena_might_shrink
arena_shrink
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/arena_resize.c.
Definition at line 818 of file arena_resize.c.
{
    return used + ARENA_SHRINK_PADDING;
}
References ARENA_SHRINK_PADDING, and used.
Referenced by arena_might_shrink().
arena_shrink_validate()
static bool arena_shrink_validate (t_arena * arena, size_t new_size) inline static
#include <arena_resize.c>
Validate whether an arena can be safely shrunk to a new size.
This internal helper wraps the logic of arena_can_shrink() with an initial null-check on the arena itself. It is used to guard shrink operations such as arena_shrink() and arena_might_shrink().
Parameters
arena Pointer to the arena to validate.
new_size Proposed size to shrink the arena to (in bytes).
Returns
true if the arena is not NULL and is allowed to shrink, false otherwise.
See also
arena_can_shrink
arena_shrink
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/arena_resize.c.
Definition at line 680 of file arena_resize.c.
{
    if (!arena)
        return false;
    if (!arena_can_shrink(arena, new_size))
        return false;
    return true;
}
References arena_can_shrink().
Referenced by arena_shrink().
should_attempt_shrink()
static bool should_attempt_shrink (t_arena * arena) inline static
#include <arena_resize.c>
Determine whether the arena is eligible for dynamic shrinking.
This helper checks if the arena is in a state that allows shrinking. Shrinking is only permitted if:
The arena pointer is not NULL.
The arena has dynamic growth enabled (can_grow is true).
This function is typically used before triggering automatic shrinking logic, such as in arena_might_shrink(), to avoid unnecessary operations.
Parameters
arena Pointer to the arena to check.
Returns
true if the arena can potentially be shrunk, false otherwise.
See also
arena_might_shrink
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/arena_resize.c.
Definition at line 754 of file arena_resize.c.
{
    if (!arena)
        return false;
    return atomic_load_explicit(&arena->can_grow, memory_order_acquire);
}
Referenced by arena_might_shrink().