memory_arena: arena_calloc.c File Reference
arena_calloc.c File Reference
Arena Allocation
Zero-initialized memory allocation functions for arenas.
#include "arena.h"
#include <string.h>
Functions
void * arena_calloc (t_arena *arena, size_t count, size_t size)
void * arena_calloc_aligned (t_arena *arena, size_t count, size_t size, size_t alignment)
void * arena_calloc_aligned_labeled (t_arena *arena, size_t count, size_t size, size_t alignment, const char *label)
void * arena_calloc_labeled (t_arena *arena, size_t count, size_t size, const char *label)
static void arena_record_failed_alloc (t_arena *arena)
Increment the arena's failed allocation counter in a thread-safe manner.
static bool validate_arena_calloc_input (t_arena *arena, size_t count, size_t size)
Validate input parameters for a calloc-style arena allocation.
Detailed Description
Zero-initialized memory allocation functions for arenas.
Author
Toonsa
Date
2025/04/24
This file implements calloc-style memory allocation within a memory arena. It provides functions to allocate memory blocks that are automatically zero-initialized, with optional support for alignment and debug labeling.
These functions are analogous to calloc in the C standard library, but operate on arenas to enable scoped, fast allocations without direct use of the heap.
Supported use cases:
Zero-initialized allocations using default alignment
Aligned zeroed allocations for SIMD or cache alignment
Allocation tracking using human-readable labels
Internal helpers are used to validate parameters, detect overflows, and track failed allocation attempts in a thread-safe manner.
Note
These functions are part of the public allocation API, but depend on internal helpers for safety checks and statistics updates.
Definition in file arena_calloc.c.
Function Documentation
arena_calloc()
void * arena_calloc (t_arena * arena, size_t count, size_t size)
Definition at line 96 of file arena_calloc.c.
{
    return arena_calloc_labeled(arena, count, size, "arena_calloc_zero");
}
References arena_calloc_labeled().
arena_calloc_aligned()
void * arena_calloc_aligned (t_arena * arena, size_t count, size_t size, size_t alignment)
Definition at line 148 of file arena_calloc.c.
{
    return arena_calloc_aligned_labeled(arena, count, size, alignment, "arena_calloc_zero");
}
References arena_calloc_aligned_labeled().
arena_calloc_aligned_labeled()
void * arena_calloc_aligned_labeled (t_arena * arena, size_t count, size_t size, size_t alignment, const char * label)
Definition at line 267 of file arena_calloc.c.
{
    if (!label)
        label = "arena_calloc_zero";
    if (!validate_arena_calloc_input(arena, count, size))
    {
        if (arena)
            arena_record_failed_alloc(arena);
        return NULL;
    }
    size_t total;
    if (would_overflow_mul(count, size, &total))
    {
        arena_record_failed_alloc(arena);
        arena_report_error(arena,
                           "arena_calloc failed: multiplication overflow "
                           "(count = %zu, size = %zu)",
                           count, size);
        return NULL;
    }
    return arena_alloc_internal(arena, total, alignment, label);
}
References arena_alloc_internal(), arena_record_failed_alloc(), arena_report_error(), validate_arena_calloc_input(), and would_overflow_mul().
arena_calloc_labeled()
void * arena_calloc_labeled (t_arena * arena, size_t count, size_t size, const char * label)
Definition at line 203 of file arena_calloc.c.
{
    return arena_calloc_aligned_labeled(arena, count, size, ARENA_DEFAULT_ALIGNMENT, label);
}
References arena_calloc_aligned_labeled(), and ARENA_DEFAULT_ALIGNMENT.
arena_record_failed_alloc()
static void arena_record_failed_alloc (t_arena * arena) inline static
Increment the arena's failed allocation counter in a thread-safe manner.
This internal utility increments the failed_allocations field in the arena’s statistics structure. It is used to track the number of failed allocation attempts (due to invalid inputs, overflows, or out-of-memory conditions).
The function uses locking (via ARENA_LOCK / ARENA_UNLOCK) to ensure thread safety when statistics are modified, if thread safety is enabled.
If the arena pointer is NULL, the function exits silently.
Parameters
arena Pointer to the t_arena whose statistics should be updated.
Note
This function is typically called from within allocation functions that detect errors before allocating memory.
See also
validate_arena_calloc_input
arena_calloc_aligned_labeled
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_calloc.c.
Definition at line 375 of file arena_calloc.c.
{
    if (!arena)
        return;
    ARENA_LOCK(arena);
    arena->stats.failed_allocations++;
    ARENA_UNLOCK(arena);
}
References ARENA_LOCK, and ARENA_UNLOCK.
validate_arena_calloc_input()
static bool validate_arena_calloc_input (t_arena * arena, size_t count, size_t size) inline static
Validate input parameters for a calloc-style arena allocation.
This internal helper verifies that the parameters provided to arena_calloc and its variants are valid before attempting memory allocation.
Specifically, it ensures:
The arena pointer is not NULL.
The count of elements to allocate is non-zero.
The size of each element is non-zero.
If any condition fails, the function reports a descriptive error using arena_report_error and returns false. Otherwise, it returns true.
Parameters
arena Pointer to the arena being used for allocation.
count Number of elements to allocate.
size Size (in bytes) of each element.
Returns
true if all inputs are valid, false otherwise.
See also
arena_calloc
arena_calloc_aligned
arena_calloc_labeled
arena_calloc_aligned_labeled
Examples
/home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_calloc.c.
Definition at line 326 of file arena_calloc.c.
{
    if (!arena)
    {
        arena_report_error(NULL, "arena_calloc failed: NULL arena provided");
        return false;
    }
    if (count == 0)
    {
        arena_report_error(arena, "arena_calloc failed: zero count (count = %zu)", count);
        return false;
    }
    if (size == 0)
    {
        arena_report_error(arena, "arena_calloc failed: zero element size (size = %zu)", size);
        return false;
    }
    return true;
}
References arena_report_error().