memory_arena: arena.h File Reference
arena.h File Reference
Core public API for the Arena memory allocator.
#include <stdlib.h>
#include <string.h>
#include "internal/arena_debug.h"
#include "arena_hooks.h"
#include "internal/arena_internal.h"
#include "internal/arena_math.h"
#include "arena_stats.h"
Data Structures
struct s_arena
Typedefs
typedef size_t(* arena_grow_callback) (size_t current_size, size_t requested_size)
typedef struct s_arena t_arena
typedef size_t t_arena_marker
Functions
void * arena_alloc (t_arena *arena, size_t size)
void * arena_alloc_aligned (t_arena *arena, size_t size, size_t alignment)
void * arena_alloc_aligned_labeled (t_arena *arena, size_t size, size_t alignment, const char *label)
void * arena_alloc_internal (t_arena *arena, size_t size, size_t alignment, const char *label)
Core internal allocator with alignment and labeling support.
void * arena_alloc_labeled (t_arena *arena, size_t size, const char *label)
bool arena_alloc_sub (t_arena *parent, t_arena *child, size_t size)
bool arena_alloc_sub_aligned (t_arena *parent, t_arena *child, size_t size, size_t alignment)
bool arena_alloc_sub_labeled (t_arena *parent, t_arena *child, size_t size, const char *label)
bool arena_alloc_sub_labeled_aligned (t_arena *parent, t_arena *child, size_t size, size_t alignment, const char *label)
void * arena_calloc (t_arena *arena, size_t count, size_t size)
void * arena_calloc_aligned (t_arena *arena, size_t count, size_t size, size_t alignment)
void * arena_calloc_aligned_labeled (t_arena *arena, size_t count, size_t size, size_t alignment, const char *label)
void * arena_calloc_labeled (t_arena *arena, size_t count, size_t size, const char *label)
t_arena * arena_create (size_t size, bool allow_grow)
void arena_delete (t_arena **arena)
void arena_destroy (t_arena *arena)
bool arena_grow (t_arena *arena, size_t required_size)
bool arena_init (t_arena *arena, size_t size, bool allow_grow)
void arena_init_with_buffer (t_arena *arena, void *buffer, size_t size, bool allow_grow)
t_arena_marker arena_mark (t_arena *arena)
bool arena_might_shrink (t_arena *arena)
size_t arena_peak (t_arena *arena)
void arena_pop (t_arena *arena, t_arena_marker marker)
void * arena_realloc_last (t_arena *arena, void *old_ptr, size_t old_size, size_t new_size)
void arena_reinit_with_buffer (t_arena *arena, void *buffer, size_t size, bool allow_grow)
size_t arena_remaining (t_arena *arena)
void arena_reset (t_arena *arena)
void arena_shrink (t_arena *arena, size_t new_size)
size_t arena_used (t_arena *arena)
Detailed Description
Core public API for the Arena memory allocator.
Author
Toonsa
Date
2025
This header defines the central data structure (t_arena) and exposes all major functions for arena-based memory allocation, deallocation, initialization, and state management.
Features:
Fast linear bump allocation
Optional dynamic resizing (grow/shrink)
Thread-safe support (via ARENA_ENABLE_THREAD_SAFE)
Memory poisoning for debugging (via ARENA_POISON_MEMORY)
Sub-arenas and marker-based rollback
Allocation labels, hooks, and diagnostics
Debug statistics, growth tracking, and stack frame support
This header is the entry point to the arena system and is included by all modules using arenas for custom allocation.
Optional modules included:
arena_tlscratch.h for thread-local scratch arenas
arena_stats.h, arena_debug.h, arena_hooks.h for profiling and tooling.
Definition in file arena.h.
Typedef Documentation
arena_grow_callback
typedef size_t(* arena_grow_callback) (size_t current_size, size_t requested_size)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h.
Definition at line 79 of file arena.h.
t_arena
typedef struct s_arena t_arena
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h.
t_arena_marker
typedef size_t t_arena_marker
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h.
Definition at line 91 of file arena.h.
Function Documentation
arena_alloc()
void * arena_alloc (t_arena * arena, size_t size)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h, /home/toonsa/myProjects/memoryArena/include/arena_io.h, /home/toonsa/myProjects/memoryArena/include/internal/arena_debug.h, /home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc_sub.c, /home/toonsa/myProjects/memoryArena/srcs/core/arena_io.c, /home/toonsa/myProjects/memoryArena/srcs/core/arena_scratch.c, /home/toonsa/myProjects/memoryArena/srcs/core/arena_tlscratch.c, arena_shrink_monitor.c, and arena_stack_parser.c.
Definition at line 62 of file arena_alloc.c.
{
    return arena_alloc_internal(arena, size, ARENA_DEFAULT_ALIGNMENT, "arena_alloc");
}
References arena_alloc_internal(), and ARENA_DEFAULT_ALIGNMENT.
Referenced by arena_stack_push(), and realloc_fallback().
arena_alloc_aligned()
void * arena_alloc_aligned (t_arena * arena, size_t size, size_t alignment)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h, and /home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc_sub.c.
Definition at line 67 of file arena_alloc.c.
{
    return arena_alloc_internal(arena, size, alignment, "arena_alloc_aligned");
}
References arena_alloc_internal().
Referenced by arena_alloc_sub_labeled_aligned().
arena_alloc_aligned_labeled()
void * arena_alloc_aligned_labeled (t_arena * arena, size_t size, size_t alignment, const char * label)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h.
Definition at line 79 of file arena_alloc.c.
{
    if (!label)
        label = "arena_alloc_aligned_labeled";
    return arena_alloc_internal(arena, size, alignment, label);
}
References arena_alloc_internal().
arena_alloc_labeled()
void * arena_alloc_labeled (t_arena * arena, size_t size, const char * label)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h, and /home/toonsa/myProjects/memoryArena/srcs/core/arena_hooks.c.
Definition at line 72 of file arena_alloc.c.
{
    if (!label)
        label = "arena_alloc_labeled";
    return arena_alloc_internal(arena, size, ARENA_DEFAULT_ALIGNMENT, label);
}
References arena_alloc_internal(), and ARENA_DEFAULT_ALIGNMENT.
arena_alloc_sub()
bool arena_alloc_sub (t_arena * parent, t_arena * child, size_t size)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h, and /home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc_sub.c.
Definition at line 135 of file arena_alloc_sub.c.
{
    return arena_alloc_sub_labeled(parent, child, size, "subarena");
}
References arena_alloc_sub_labeled().
arena_alloc_sub_aligned()
bool arena_alloc_sub_aligned (t_arena * parent, t_arena * child, size_t size, size_t alignment)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h, and /home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc_sub.c.
Definition at line 140 of file arena_alloc_sub.c.
{
    return arena_alloc_sub_labeled_aligned(parent, child, size, alignment, "subarena");
}
References arena_alloc_sub_labeled_aligned().
arena_alloc_sub_labeled()
bool arena_alloc_sub_labeled (t_arena * parent, t_arena * child, size_t size, const char * label)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h, and /home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc_sub.c.
Definition at line 145 of file arena_alloc_sub.c.
{
    return arena_alloc_sub_labeled_aligned(parent, child, size, ARENA_DEFAULT_ALIGNMENT, label);
}
References arena_alloc_sub_labeled_aligned(), and ARENA_DEFAULT_ALIGNMENT.
Referenced by arena_alloc_sub().
arena_alloc_sub_labeled_aligned()
bool arena_alloc_sub_labeled_aligned (t_arena * parent, t_arena * child, size_t size, size_t alignment, const char * label)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h, and /home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc_sub.c.
Definition at line 150 of file arena_alloc_sub.c.
{
    if (!arena_alloc_sub_validate(parent, child))
        return false;
    void* mem = arena_alloc_aligned(parent, size, alignment);
    if (!mem)
    {
        arena_report_error(parent, "arena_alloc_sub failed: allocation from parent arena failed");
        return false;
    }
    arena_setup_subarena(parent, child, mem, size, label);
    ALOG("[arena_alloc_sub] Created sub-arena (%s) of %zu bytes from %p → %p\n", child->debug.label, size,
         (void*) parent, (void*) child);
    return true;
}
References ALOG, arena_alloc_aligned(), arena_alloc_sub_validate(), arena_report_error(), and arena_setup_subarena().
Referenced by arena_alloc_sub_aligned(), and arena_alloc_sub_labeled().
arena_calloc()
void * arena_calloc (t_arena * arena, size_t count, size_t size)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h, and /home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc_sub.c.
Definition at line 45 of file arena_calloc.c.
{
    return arena_calloc_labeled(arena, count, size, "arena_calloc_zero");
}
References arena_calloc_labeled().
arena_calloc_aligned()
void * arena_calloc_aligned (t_arena * arena, size_t count, size_t size, size_t alignment)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h.
Definition at line 50 of file arena_calloc.c.
{
    return arena_calloc_aligned_labeled(arena, count, size, alignment, "arena_calloc_zero");
}
References arena_calloc_aligned_labeled().
arena_calloc_aligned_labeled()
void * arena_calloc_aligned_labeled (t_arena * arena, size_t count, size_t size, size_t alignment, const char * label)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h.
Definition at line 60 of file arena_calloc.c.
{
    if (!label)
        label = "arena_calloc_zero";
    if (!validate_arena_calloc_input(arena, count, size))
    {
        if (arena)
            arena_record_failed_alloc(arena);
        return NULL;
    }
    size_t total;
    if (would_overflow_mul(count, size, &total))
    {
        arena_record_failed_alloc(arena);
        arena_report_error(arena,
                           "arena_calloc failed: multiplication overflow "
                           "(count = %zu, size = %zu)",
                           count, size);
        return NULL;
    }
    return arena_alloc_internal(arena, total, alignment, label);
}
References arena_alloc_internal(), arena_record_failed_alloc(), arena_report_error(), validate_arena_calloc_input(), and would_overflow_mul().
Referenced by arena_calloc_aligned(), and arena_calloc_labeled().
arena_calloc_labeled()
void * arena_calloc_labeled (t_arena * arena, size_t count, size_t size, const char * label)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h.
Definition at line 55 of file arena_calloc.c.
{
    return arena_calloc_aligned_labeled(arena, count, size, ARENA_DEFAULT_ALIGNMENT, label);
}
References arena_calloc_aligned_labeled(), and ARENA_DEFAULT_ALIGNMENT.
Referenced by arena_calloc().
arena_create()
t_arena * arena_create (size_t size, bool allow_grow)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h, /home/toonsa/myProjects/memoryArena/include/arena_stack.h, /home/toonsa/myProjects/memoryArena/include/internal/arena_debug.h, /home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc_sub.c, /home/toonsa/myProjects/memoryArena/srcs/core/arena_hooks.c, /home/toonsa/myProjects/memoryArena/srcs/internal/arena_debug.c, arena_shrink_monitor.c, and arena_stack_parser.c.
Definition at line 62 of file arena_create.c.
{
    if (size == 0)
    {
        arena_report_error(NULL, "arena_create failed: zero size requested");
        return NULL;
    }
    t_arena* arena = arena_alloc_struct();
    if (!arena)
        return NULL;
    void* buffer = arena_alloc_buffer(size);
    if (!buffer)
    {
        arena_log_and_teardown(&arena, "arena_create: buffer allocation failed");
        return NULL;
    }
    if (!arena_finish_init(arena, buffer, size, allow_grow))
    {
        arena_log_and_teardown(&arena, "arena_create: init failure");
        return NULL;
    }
    arena_set_default_label(arena, "arena_heap");
    arena_generate_id(arena);
    return arena;
}
References arena_alloc_buffer(), arena_alloc_struct(), arena_finish_init(), arena_generate_id(), arena_log_and_teardown(), arena_report_error(), and arena_set_default_label().
arena_delete()
void arena_delete (t_arena ** arena)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h, /home/toonsa/myProjects/memoryArena/include/arena_stack.h, /home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc_sub.c, /home/toonsa/myProjects/memoryArena/srcs/core/arena_hooks.c, arena_shrink_monitor.c, and arena_stack_parser.c.
Definition at line 68 of file arena_cleanup.c.
{
    if (!arena || !*arena)
        return;
    arena_destroy(*arena);
    free(*arena);
    *arena = NULL;
}
References arena_destroy().
Referenced by arena_log_and_teardown().
arena_destroy()
void arena_destroy (t_arena * arena)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h, /home/toonsa/myProjects/memoryArena/include/arena_io.h, /home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc_sub.c, /home/toonsa/myProjects/memoryArena/srcs/core/arena_io.c, /home/toonsa/myProjects/memoryArena/srcs/core/arena_scratch.c, and /home/toonsa/myProjects/memoryArena/srcs/core/arena_tlscratch.c.
Definition at line 36 of file arena_cleanup.c.
{
    if (!arena)
        return;
    bool expected = false;
    if (!atomic_compare_exchange_strong(&arena->is_destroying, &expected, true))
        return;
#ifdef ARENA_ENABLE_THREAD_SAFE
    if (arena->use_lock)
    {
        ARENA_CHECK(arena);
        ARENA_LOCK(arena);
        arena_free_buffer_if_owned(arena);
        arena_free_growth_history(arena);
        arena_zero_metadata(arena);
        ARENA_UNLOCK(arena);
        arena->use_lock = false;
        pthread_mutex_destroy(&arena->lock);
        return;
    }
#endif
    arena_free_buffer_if_owned(arena);
    arena_free_growth_history(arena);
    arena_zero_metadata(arena);
}
References ARENA_CHECK, arena_free_buffer_if_owned(), arena_free_growth_history(), ARENA_LOCK, ARENA_UNLOCK, and arena_zero_metadata().
Referenced by arena_delete(), arena_log_and_teardown(), arena_reinit_with_buffer(), and scratch_pool_destroy().
arena_grow()
bool arena_grow (t_arena * arena, size_t required_size)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h.
Definition at line 59 of file arena_resize.c.
{
    if (!arena)
        return false;
    if (required_size == 0)
        return true;
    ARENA_LOCK(arena);
    if (!arena_grow_validate(arena, required_size))
    {
        ARENA_UNLOCK(arena);
        return false;
    }
    size_t old_size = arena->size;
    size_t new_size = arena_grow_compute_new_size(arena, required_size);
    if (new_size == 0)
    {
        arena_report_error(arena, "arena_grow failed: computed size invalid");
        ARENA_UNLOCK(arena);
        return false;
    }
    if (new_size > (size_t)(1ULL << 32)) // 4GiB
    {
        arena_report_error(arena, "arena_grow rejected size: %zu", new_size);
        return false;
    }
    bool success = arena_grow_realloc_buffer(arena, new_size, old_size);
    ARENA_UNLOCK(arena);
    return success;
}
References arena_grow_compute_new_size(), arena_grow_realloc_buffer(), arena_grow_validate(), ARENA_LOCK, arena_report_error(), and ARENA_UNLOCK.
Referenced by arena_try_grow(), and realloc_in_place().
arena_init()
bool arena_init (t_arena * arena, size_t size, bool allow_grow)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h, /home/toonsa/myProjects/memoryArena/include/arena_io.h, /home/toonsa/myProjects/memoryArena/srcs/core/arena_io.c, /home/toonsa/myProjects/memoryArena/srcs/core/arena_scratch.c, and /home/toonsa/myProjects/memoryArena/srcs/core/arena_tlscratch.c.
Definition at line 92 of file arena_create.c.
{
    if (!arena || size == 0)
    {
        arena_report_error(NULL, "arena_init failed: invalid arena or size");
        return false;
    }
    void* buffer = arena_alloc_buffer(size);
    if (!buffer)
    {
        arena_log_and_teardown(&arena, "arena_init: buffer allocation failed");
        return NULL;
    }
    if (!arena_finish_init(arena, buffer, size, allow_grow))
    {
        arena_report_error(arena, "arena_init: arena_finish_init failed");
        free(buffer);
        return false;
    }
    arena_set_default_label(arena, "arena_stack");
    arena_generate_id(arena);
    return true;
}
References arena_alloc_buffer(), arena_finish_init(), arena_generate_id(), arena_log_and_teardown(), arena_report_error(), and arena_set_default_label().
Referenced by scratch_slot_init().
arena_init_with_buffer()
void arena_init_with_buffer (t_arena * arena, void * buffer, size_t size, bool allow_grow)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h, and /home/toonsa/myProjects/memoryArena/srcs/core/allocation/arena_alloc_sub.c.
Definition at line 119 of file arena_create.c.
{
    if (!arena)
    {
        arena_report_error(NULL, "arena_init_with_buffer: NULL arena");
        return;
    }
    arena_reset_metadata(arena);
    atomic_store_explicit(&arena->can_grow, allow_grow, memory_order_release);
    arena_init_mutex(arena);
    if (!arena_set_or_alloc_buffer(arena, buffer, size))
        return;
    arena_set_default_label(arena, "arena_from_buffer");
    arena_generate_id(arena);
}
References arena_generate_id(), arena_init_mutex(), arena_report_error(), arena_reset_metadata(), arena_set_default_label(), and arena_set_or_alloc_buffer().
Referenced by arena_reinit_with_buffer(), and arena_setup_subarena().
arena_mark()
t_arena_marker arena_mark (t_arena * arena)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h.
Definition at line 68 of file arena_state.c.
{
    if (!arena)
        return 0;
    ARENA_LOCK(arena);
    size_t offset = arena->offset;
    ARENA_UNLOCK(arena);
    return offset;
}
References ARENA_LOCK, and ARENA_UNLOCK.
Referenced by arena_stack_push().
arena_might_shrink()
bool arena_might_shrink (t_arena * arena)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h, and arena_shrink_monitor.c.
Definition at line 108 of file arena_resize.c.
{
    if (!should_attempt_shrink(arena))
        return false;
    ARENA_LOCK(arena);
    ARENA_CHECK(arena);
    const size_t used = arena->offset;
    const size_t size = arena->size;
    if (arena_should_maybe_shrink(used, size))
    {
        const size_t target = arena_shrink_target(used);
        if (target < size)
        {
            arena_shrink(arena, target);
            ARENA_UNLOCK(arena);
            return true;
        }
    }
    ARENA_UNLOCK(arena);
    return false;
}
References ARENA_CHECK, ARENA_LOCK, arena_should_maybe_shrink(), arena_shrink(), arena_shrink_target(), ARENA_UNLOCK, should_attempt_shrink(), and used.
arena_peak()
size_t arena_peak (t_arena * arena)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h.
Definition at line 57 of file arena_state.c.
{
    if (!arena)
        return 0;
    ARENA_LOCK(arena);
    size_t peak = arena->stats.peak_usage;
    ARENA_UNLOCK(arena);
    return peak;
}
References ARENA_LOCK, and ARENA_UNLOCK.
Referenced by draw_visualizer().
arena_pop()
void arena_pop (t_arena * arena, t_arena_marker marker)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h.
Definition at line 79 of file arena_state.c.
{
    if (!arena)
        return;
    ARENA_LOCK(arena);
    if (marker > arena->offset)
    {
        arena_report_error(arena, "arena_pop failed: invalid marker %zu (offset: %zu)", marker, arena->offset);
        ARENA_UNLOCK(arena);
        return;
    }
    arena_poison_memory(arena->buffer + marker, arena->offset - marker);
    arena->offset = marker;
    ARENA_UNLOCK(arena);
}
References ARENA_LOCK, arena_poison_memory, arena_report_error(), and ARENA_UNLOCK.
Referenced by arena_stack_pop().
arena_realloc_last()
void * arena_realloc_last (t_arena * arena, void * old_ptr, size_t old_size, size_t new_size)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h.
Definition at line 52 of file arena_realloc_last.c.
{
    if (!arena_realloc_validate(arena, old_ptr, new_size))
        return NULL;
    ARENA_LOCK(arena);
    ARENA_CHECK(arena);
    bool  is_last = is_last_allocation(arena, old_ptr, old_size);
    void* result  = is_last ? realloc_in_place(arena, old_ptr, old_size, new_size) : NULL;
    ARENA_UNLOCK(arena);
    return is_last ? result : realloc_fallback(arena, old_ptr, old_size, new_size);
}
References ARENA_CHECK, ARENA_LOCK, arena_realloc_validate(), ARENA_UNLOCK, is_last_allocation(), realloc_fallback(), and realloc_in_place().
arena_reinit_with_buffer()
void arena_reinit_with_buffer (t_arena * arena, void * buffer, size_t size, bool allow_grow)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h.
Definition at line 138 of file arena_create.c.
{
    arena_destroy(arena);
    arena_init_with_buffer(arena, buffer, size, allow_grow);
}
References arena_destroy(), and arena_init_with_buffer().
arena_remaining()
size_t arena_remaining (t_arena * arena)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h.
Definition at line 46 of file arena_state.c.
{
    if (!arena)
        return 0;
    ARENA_LOCK(arena);
    size_t remaining = arena->size - arena->offset;
    ARENA_UNLOCK(arena);
    return remaining;
}
References ARENA_LOCK, and ARENA_UNLOCK.
Referenced by draw_visualizer().
arena_reset()
void arena_reset (t_arena * arena)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h, /home/toonsa/myProjects/memoryArena/srcs/core/arena_scratch.c, /home/toonsa/myProjects/memoryArena/srcs/core/arena_tlscratch.c, and arena_shrink_monitor.c.
Definition at line 97 of file arena_state.c.
{
    if (!arena)
        return;
    ARENA_LOCK(arena);
    ARENA_ASSERT_VALID(arena);
    arena_poison_memory(arena->buffer, arena->size);
    arena->offset = 0;
    ARENA_UNLOCK(arena);
}
References ARENA_ASSERT_VALID, ARENA_LOCK, arena_poison_memory, and ARENA_UNLOCK.
Referenced by scratch_acquire().
arena_shrink()
void arena_shrink (t_arena * arena, size_t new_size)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h.
Definition at line 94 of file arena_resize.c.
{
    if (!arena)
        return;
    ARENA_LOCK(arena);
    ARENA_CHECK(arena);
    bool ok = arena_shrink_validate(arena, new_size) && arena_shrink_apply(arena, new_size);
    (void) ok;
    ARENA_UNLOCK(arena);
}
References ARENA_CHECK, ARENA_LOCK, arena_shrink_apply(), arena_shrink_validate(), and ARENA_UNLOCK.
Referenced by arena_might_shrink().
arena_used()
size_t arena_used (t_arena * arena)
Examples
/home/toonsa/myProjects/memoryArena/include/arena.h.
Definition at line 35 of file arena_state.c.
{
    if (!arena)
        return 0;
    ARENA_LOCK(arena);
    size_t used = arena->offset;
    ARENA_UNLOCK(arena);
    return used;
}
References ARENA_LOCK, ARENA_UNLOCK, and used.
Referenced by arena_visualizer_allocation_hook(), and draw_visualizer().