memory_arena: arena_alloc_sub.c File Reference
arena_alloc_sub.c File Reference
#include "arena.h"
#include <stdio.h>
Functions
bool arena_alloc_sub (t_arena *parent, t_arena *child, size_t size)
bool arena_alloc_sub_aligned (t_arena *parent, t_arena *child, size_t size, size_t alignment)
bool arena_alloc_sub_labeled (t_arena *parent, t_arena *child, size_t size, const char *label)
bool arena_alloc_sub_labeled_aligned (t_arena *parent, t_arena *child, size_t size, size_t alignment, const char *label)
static bool arena_alloc_sub_validate (t_arena *parent, t_arena *child)
Validate the input parameters for creating a sub-arena.
static void arena_generate_subarena_id (t_arena *parent, t_arena *child)
Generate a unique debug identifier for a sub-arena.
static void arena_setup_subarena (t_arena *parent, t_arena *child, void *buffer, size_t size, const char *label)
Initialize a child arena as a sub-arena of a parent using a provided memory block.
Function Documentation
arena_alloc_sub()
bool arena_alloc_sub (t_arena * parent, t_arena * child, size_t size)
Definition at line 135 of file arena_alloc_sub.c.
{
    return arena_alloc_sub_labeled(parent, child, size, "subarena");
}
References arena_alloc_sub_labeled().
arena_alloc_sub_aligned()
bool arena_alloc_sub_aligned (t_arena * parent, t_arena * child, size_t size, size_t alignment)
Definition at line 140 of file arena_alloc_sub.c.
{
    return arena_alloc_sub_labeled_aligned(parent, child, size, alignment, "subarena");
}
References arena_alloc_sub_labeled_aligned().
arena_alloc_sub_labeled()
bool arena_alloc_sub_labeled (t_arena * parent, t_arena * child, size_t size, const char * label)
Definition at line 145 of file arena_alloc_sub.c.
{
    return arena_alloc_sub_labeled_aligned(parent, child, size, ARENA_DEFAULT_ALIGNMENT, label);
}
References arena_alloc_sub_labeled_aligned(), and ARENA_DEFAULT_ALIGNMENT.
Referenced by arena_alloc_sub().
arena_alloc_sub_labeled_aligned()
bool arena_alloc_sub_labeled_aligned (t_arena * parent, t_arena * child, size_t size, size_t alignment, const char * label)
Definition at line 150 of file arena_alloc_sub.c.
{
    if (!arena_alloc_sub_validate(parent, child))
        return false;
    void* mem = arena_alloc_aligned(parent, size, alignment);
    if (!mem)
    {
        arena_report_error(parent, "arena_alloc_sub failed: allocation from parent arena failed");
        return false;
    }
    arena_setup_subarena(parent, child, mem, size, label);
    ALOG("[arena_alloc_sub] Created sub-arena (%s) of %zu bytes from %p → %p\n", child->debug.label, size,
         (void*) parent, (void*) child);
    return true;
}
References ALOG, arena_alloc_aligned(), arena_alloc_sub_validate(), arena_report_error(), and arena_setup_subarena().
Referenced by arena_alloc_sub_aligned(), and arena_alloc_sub_labeled().